Repository inureyes/gradios, pull requests merged in 2019-04, with the labels that each got.

#2 refs #1 : add - credit to original author
  README.md
Labels: enhancement, good first issue

#4 refs #3 : modify - README.md
  README.md
Labels: enhancement, good first issue

#42 resolve #5
  README.md
Labels: enhancement, good first issue

#47 resolve #41
  README.md
Labels: enhancement

#44 resolve #8
  README.md
Labels: enhancement

#43 resolve #10
  README.md
Labels: enhancement

#64 Resolve #6
  README.md
Labels: enhancement

#45 resolve #9
  README.md
Labels: enhancement, good first issue

#66 resolve #61
  index.html
Labels: enhancement, good first issue

#58 resolve #30
  README.md
Labels: enhancement, good first issue

#53 resolve #36
  README.md
Labels: enhancement, good first issue

#67 resolve #22
  README.md
Labels: enhancement

#56 resolve #16
  README.md
Labels: enhancement, good first issue

#52 resolve #18
  README.md
Labels: enhancement

#74 resolve #32
  README.md
Labels: enhancement, good first issue

#65 resolve #7
  README.md
Labels: enhancement

#49 resolve #35
  .github/ISSUE_TEMPLATE/--------.md
  .github/ISSUE_TEMPLATE/-----.md
  README.md
Labels: enhancement, good first issue

#50 resolve #29
  README.md
Labels: enhancement, good first issue

#77 resolve #14
  README.md
Labels: enhancement, good first issue

#75 resolve #19
  README.md
Labels: enhancement, good first issue

#69 reslove#11
  README.md
Labels: enhancement

#80 resolve #24
  README.md
Labels: enhancement, good first issue

#81 resolve #34
  README.md
Labels: enhancement, good first issue

#85 add my name
  README.md
Labels: enhancement, good first issue

#84 resolve # 15
  README.md
Labels: enhancement

#73 resolve #27
  README.md
  index.html
Labels: enhancement, good first issue

#88 resolve #86
  README.md
Labels: enhancement, good first issue

#89 resolve #21
  README.md
Labels: enhancement, good first issue

#90 resolve #25
  README.md
Labels: enhancement, good first issue

#93 resolve #26
  README.md
Labels: enhancement, good first issue

#166 resolve #125
  README.md
Labels: enhancement, good first issue

#136 resolve #102
  README.md
Labels: enhancement, good first issue

#159 resolve #109
  README.md
Labels: enhancement, good first issue

#161 resolve #127
  README.md
Labels: enhancement, good first issue

#163 resolve #113
  README.md
Labels: enhancement, good first issue

#168 resolve #131
  README.md
Labels: enhancement, good first issue

#172 resolve #123
  README.md
Labels: enhancement, good first issue

#171 ref #154 add-new-name
  README.md
Labels: enhancement, good first issue

#174 resolve #110
  README.md
Labels: enhancement, good first issue

#165 resolve #105
  .README.md.swp
  README.md
Labels: enhancement, good first issue

#182 Resolve #108
  README.md
Labels: enhancement, good first issue

#178 Resolve #145
  README.md
Labels: enhancement, good first issue

#197 resolve #133
  README.md
Labels: enhancement, good first issue

#190 resolve #139
  README.md
Labels: enhancement, good first issue

#186 Resolve #169
  README.md
Labels: enhancement

#203 resolve#132
  README.md
Labels: enhancement, good first issue

#179 resovle #119
  README.md
Labels: enhancement, good first issue

#192 Resolve #140
  README.md
Labels: enhancement, good first issue

#205 resolve #144
  README.md
Labels: enhancement, good first issue

#210 resolve #117
  README.md
Labels: enhancement, good first issue

#213 resolve #126
  README.md
Labels: enhancement, good first issue

#219 resolve #121
  README.md
Labels: enhancement, good first issue

#217 resolve#214
  README.md
Labels: enhancement, good first issue

#223 resolve #183
  .DS_Store
  js/game-logic.js
  js/index.html
Labels: bug

#227 Resolve #143
  README.md
Labels: enhancement, good first issue

#235 resolve #233
  js/game-logic.js
Labels: bug

#237 resolve #220
  js/game-logic.js
Labels: bug

#238 resolve #225
  js/game-logic.js
Labels: enhancement

#239 Resolve #98
  README.md
  js/game-logic.js
Labels: bug

#242 resolve #99
  js/game-logic.js
Labels: bug

#247 resolve #244
  wiki.md
Labels: enhancement

#248 Paths referencing resources are fixed and Removed redundant code
  index.html
  public/js/game-logic.js
Labels: bug

#250 resource references are fixed... again
  index.html
  public/js/game-logic.js
Labels: bug

#100 resolve #94
  public/js/game-logic.js
Labels: bug

#259 resolve #258
  public/js/game-logic.js
Labels: bug

#261 resolve #260
  public/js/game-logic.js
Labels: bug

#275 refs #271 extra score added
  public/js/game.js
Labels: enhancement

#277 refs #276: modify about continuing game
  public/js/game.js
Labels: enhancement

#293 resolve #187
  node_modules/vary/package.json
Labels: enhancement

#295 resolve #294
  public/js/game.js
Labels: bug

#316 resolved # 296 enemy bomb speed up
  .idea/encodings.xml
  .idea/gradios.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  app.js
  bin/www
  nintendo.otf
  package-lock.json
  package.json
  public/img/menubutton.png
  public/img/restartbutton.png
  public/img/startbutton.png
  public/js/ending.js
  public/js/game.js
  public/js/main.js
  public/js/menu.js
  public/js/phaser.min.js
  routes/index.js
  views/error.ejs
  views/index.ejs
  wiki.md
Labels: enhancement

#319 resolve # 296
  public/js/game.js
Labels: enhancement

#315 resolve #310
  .gitignore
Labels: enhancement

#326 #308 resolve
  public/js/ending.js
  public/js/menu.js
Labels: enhancement

#332 #328 resolve 'centered the final score location'
  public/js/ending.js
Labels: bug

#334 #331 resolve
  public/audio/stage-clear.wav
  public/js/game.js
Labels: enhancement

#336 resolved #322
  public/img/heart.png
  public/js/game.js
Labels: enhancement

#342 Resolved #341
  public/js/game.js
Labels: bug

#345 resolve #343
  public/js/game.js
Labels: bug

#347 resolve #346
  public/js/game.js
Labels: enhancement

#359 resolved #358
  public/js/game.js
Labels: enhancement

#366 resolve #363
  public/js/game.js
Labels: enhancement

#382 resolve #380
  public/js/game.js
Labels: enhancement

#398 refs#273: add wall_paper
  public/js/main.js
  public/js/menu.js
Labels: enhancement

#402 resolve #401
  public/js/game.js
Labels: enhancement

#412 resolve #290
  public/img/power_up.png
  public/js/game.js
Labels: enhancement

#423 #421 resolve
  public/js/game.js
Labels: bug

#425 resolve #424
  public/js/game.js
Labels: bug

#427 resolved #413
  public/js/game.js
Labels: enhancement

#435 resolve #418
  public/img/speedup.png
  public/js/game.js
Labels: enhancement

#437 resolve #392
  public/js/game.js
Labels: bug

#438 resolve refs #406 : show control keys
  public/img/controlkey.png
Labels: enhancement

#439 resolve #431
  public/js/game.js
Labels: enhancement

#440 #439 slow down item change
  public/js/game.js
Labels: enhancement

#450 resolve #446
  public/js/game.js
Labels: bug

#452 refs #451: Reset player's power & speed when enemy hits player
  public/js/game.js
Labels: bug

#461 #393 related - added extra score functions with images
  public/img/score_up_2.png
  public/img/score_up_3.png
  public/img/speed_up.png
  public/js/game.js
Labels: enhancement

#463 #330 resolve (1): various enemy movements added
  public/js/game.js
Labels: enhancement

#468 bullet upgrade
  public/js/game.js
Labels: enhancement

#475 resolve #471 add new start/restart btn
  public/img/restartButton.png
  public/img/restartbutton.png
  public/img/startButton.png
  public/img/startbutton.png
Labels: enhancement

#478 #477 resolve
  public/js/menu.js
Labels: enhancement

#486 refs #473: modify velocity
  public/js/game.js
Labels: bug

#491 refs #489 resolve
  public/js/game.js
Labels: enhancement

#492 [FEATURE] Fixed the buttons to the middle
  public/js/ending.js
  public/js/menu.js
Labels: enhancement
