Repository inureyes/gradios, pull requests merged in 2019-05, with the labels that each got.

#521 modified menu & control button position
  public/js/menu.js
Labels: enhancement

#525 #524 add image
  public/js/menu.js
Labels: enhancement

#527 #526 add ending sound
  public/audio/ending_sound.mp3
  public/js/ending.js
Labels: enhancement

#530 위치수정
  public/js/game.js
  public/js/menu.js
Labels: enhancement

#542 refs #531
  public/js/game.js
Labels: enhancement

#555 refs #552
  public/img/controlkey-1.png
  public/js/game.js
  public/js/menu.js
Labels: enhancement

#557 #556 add exit button
  public/img/exit.png
  public/js/menu.js
Labels: enhancement

#559 refs #558 : Add Bounus Score Text
  public/js/game.js
Labels: enhancement

#563 refs #556
  public/img/exit.png
  public/js/menu.js
Labels: enhancement

#584 refs #553
  webserver/js/menu.js
Labels: enhancement

#594 refs #592 resolve
  webserver/img/shield.png
Labels: enhancement

#604 backButton update
  webserver/img/backButton.png
Labels: enhancement

#609 아이템 습득시 사운드가 설정창 효과음에 반영안되있던것을 수정
  webserver/js/game.js
Labels: enhancement

#642 modify control image
  webserver/img/controlkey-1.png
Labels: enhancement

#645 improved armerShip image
  webserver/img/armerShip264x64x5.png
  webserver/img/armerShip264x64x5_ori.png
  webserver/img/armerShip64x64x5.png
  webserver/img/armerShip64x64x5_ori.png
Labels: enhancement

#646 characterSelection text added
  webserver/js/game.js
Labels: enhancement

#648 add button , modify code
  webserver/img/ship.png
  webserver/img/ship2.png
  webserver/js/game.js
Labels: enhancement

#649 refs #554
  webserver/img/shield-1.png
  webserver/js/game.js
Labels: enhancement

#652 ship2 image modified
  webserver/img/ship2.png
  webserver/img/ship2_ori.png
  webserver/js/game.js
Labels: enhancement

#658 refs #657 Collapsible readme
  README.md
  webserver/.DS_Store
Labels: enhancement

#667 refs #666
  webserver/js/game.js
Labels: enhancement

#673 refs #672
  webserver/js/game.js
Labels: enhancement

#676 refs #622
  webserver/img/controlkey-1.png
  webserver/img/controlkey.png
  webserver/img/help.png
  webserver/img/mainmenu.png
  webserver/img/offButton.png
  webserver/img/onButton.png
  webserver/img/restartButton-1.png
  webserver/img/resumeButton.png
  webserver/img/shield-1.png
  webserver/js/menu.js
Labels: enhancement

#687 refs #671 : modify logo image
  webserver/img/gradius.png
Labels: enhancement

#727 Updated image for ranking reset button
  webserver/img/reset_ranking.png
  webserver/js/ending.js
Labels: enhancement

#736 resolve #735
  webserver/js/game.js
  webserver/js/player.js
Labels: bug

#751 #742 resolve
  webserver/audio/bullet-die.wav
  webserver/audio/enemy-die.wav
  webserver/js/game.js
Labels: enhancement

#752 refs #651 : 아이템 이미지 추가
  webserver/img/item/addBullet.PNG
  webserver/img/item/addPenetration.PNG
  webserver/js/game.js
Labels: enhancement

#759 music off할때 bgm volume 0안되는것 수정
  webserver/.DS_Store
  webserver/js/game.js
Labels: bug, enhancement

#787 #767 resolve
  README.md
Labels: enhancement

#817 refs #814 #815
  webserver/js/menu.js
Labels: bug, enhancement

#826 #496 비행기 종류 추가
  new_design/plane/Plain3.png
  new_design/plane/Plane1.png
  new_design/plane/Plane2.png
Labels: enhancement

#843 refs #842 비행기 선택
  webserver/js/game.js
  webserver/js/player.js
Labels: enhancement

#866 refs #791
  webserver/img/newship264x64x5-1.png
  webserver/img/ship4.png
  webserver/js/game.js
  webserver/js/player.js
Labels: enhancement

#873 refs #871 치트모드 부가기능
  webserver/js/game.js
  webserver/js/itemFormat.js
Labels: enhancement

#874 refs #861
  webserver/js/game.js
Labels: bug, enhancement
